### PR TITLE
assertEquals is deprecated

### PR DESCRIPTION
**Pull request by Vesihiisi**
Get rid of mild warning when running test.

### CODE REVIEW

**Comment by lokal-profil** [comment]
Would you mind doing the same to the other test file as part of the same PR?

Note that I've since committed to that one though.

**Comment by Vesihiisi** [comment]
I've fixed the deprecated asserts, but I'm having some problems with test_add_new_claim_reraise_error_on_duplicate_matching_claim(). [I had to do this](https://github.com/lokal-profil/wikidata-stuff/pull/28/commits/2fda3ade42e83e1b46a445071f21b2bd1198bf4a#diff-388f8f67260b13189351a672b39aa70bR514) to get the test to pass, but then the build failed. Not sure why your original version fails in my environment, though.

**Comment by lokal-profil** [comment]
I think the actual culprit might be pywikibot having tweaked their error messages. Build always uses the latest.

I've fixed it in the py3compat branch. If you wouldn't mind rebasing again (and do a quick check for any new deprecated asserts) I promise not to push anything to the branch until after I've merged this.

**Comment by Vesihiisi** [comment]
Yeah, there's some weirdness with the error messages I couldn't quite replicate, but I've cleaned up the deprecation warnings.

**Pull request merged**
